// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// engine_objective_cpp
Rcpp::List engine_objective_cpp(const arma::mat& X, const arma::mat& W, const arma::rowvec& b, const arma::mat& P, const arma::mat& DBbeta, double lambda_W, double lambda_HRF, double lambda_smooth, const arma::sp_mat& L);
RcppExport SEXP _hrfdecoder_engine_objective_cpp(SEXP XSEXP, SEXP WSEXP, SEXP bSEXP, SEXP PSEXP, SEXP DBbetaSEXP, SEXP lambda_WSEXP, SEXP lambda_HRFSEXP, SEXP lambda_smoothSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DBbeta(DBbetaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_W(lambda_WSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_HRF(lambda_HRFSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_smooth(lambda_smoothSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(engine_objective_cpp(X, W, b, P, DBbeta, lambda_W, lambda_HRF, lambda_smooth, L));
    return rcpp_result_gen;
END_RCPP
}
// fit_softlabels_als
Rcpp::List fit_softlabels_als(const arma::mat& X, const arma::mat& P0, const arma::sp_mat& L, const arma::mat& DBbeta, double lambda_W, double lambda_HRF, double lambda_smooth, int max_iter, double tol, bool nonneg, bool threads);
RcppExport SEXP _hrfdecoder_fit_softlabels_als(SEXP XSEXP, SEXP P0SEXP, SEXP LSEXP, SEXP DBbetaSEXP, SEXP lambda_WSEXP, SEXP lambda_HRFSEXP, SEXP lambda_smoothSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP nonnegSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P0(P0SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DBbeta(DBbetaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_W(lambda_WSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_HRF(lambda_HRFSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_smooth(lambda_smoothSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type nonneg(nonnegSEXP);
    Rcpp::traits::input_parameter< bool >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_softlabels_als(X, P0, L, DBbeta, lambda_W, lambda_HRF, lambda_smooth, max_iter, tol, nonneg, threads));
    return rcpp_result_gen;
END_RCPP
}
// predict_softlabels
arma::mat predict_softlabels(const arma::mat& Xtest, const arma::mat& W, const arma::rowvec& b);
RcppExport SEXP _hrfdecoder_predict_softlabels(SEXP XtestSEXP, SEXP WSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtest(XtestSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_softlabels(Xtest, W, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hrfdecoder_engine_objective_cpp", (DL_FUNC) &_hrfdecoder_engine_objective_cpp, 9},
    {"_hrfdecoder_fit_softlabels_als", (DL_FUNC) &_hrfdecoder_fit_softlabels_als, 11},
    {"_hrfdecoder_predict_softlabels", (DL_FUNC) &_hrfdecoder_predict_softlabels, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hrfdecode(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
