# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

engine_objective <- function(X, W, b, P, DBbeta, lambda_W, lambda_HRF, lambda_smooth, L) {
    .Call(`_hrfdecoder_engine_objective_cpp`, X, W, b, P, DBbeta, lambda_W, lambda_HRF, lambda_smooth, L)
}

fit_softlabels_als <- function(X, P0, L, DBbeta, lambda_W, lambda_HRF, lambda_smooth, max_iter, tol, nonneg, threads) {
    .Call(`_hrfdecoder_fit_softlabels_als`, X, P0, L, DBbeta, lambda_W, lambda_HRF, lambda_smooth, max_iter, tol, nonneg, threads)
}

predict_softlabels <- function(Xtest, W, b) {
    .Call(`_hrfdecoder_predict_softlabels`, Xtest, W, b)
}

